set(_CATKIN_CURRENT_PACKAGE "selly")
set(selly_VERSION "0.0.0")
set(selly_MAINTAINER "hyeok <hyeok@todo.todo>")
set(selly_PACKAGE_FORMAT "2")
set(selly_BUILD_DEPENDS "message_generation" "message_generation" "rospy" "std_msgs")
set(selly_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(selly_BUILDTOOL_DEPENDS "catkin")
set(selly_BUILDTOOL_EXPORT_DEPENDS )
set(selly_EXEC_DEPENDS "message_runtime" "rospy" "std_msgs")
set(selly_RUN_DEPENDS "message_runtime" "rospy" "std_msgs")
set(selly_TEST_DEPENDS )
set(selly_DOC_DEPENDS )
set(selly_URL_WEBSITE "")
set(selly_URL_BUGTRACKER "")
set(selly_URL_REPOSITORY "")
set(selly_DEPRECATED "")